#RuntimeError се получава, когато програмата работи, но в последствия се прекратява спрямо липсата на логика 
# и селдователно се получава тази грешка
#Също така Python хвърля Runtime error, когато се засече грешка, но тя не попада във вече създадените грешки
